### ISSUE TITLE
The use of interfaces is inconsistent.

### ISSUE THREAD

**Issue by myrle-krantz** [stellar/java-stellar-sdk#3]
Specifically TransactionBuilderAccount is an interface for exactly one class.  Interfaces are also a potential backwards compatibility problem (adding methods breaks backwards compatibility unless you use the java 8 feature of adding default implementations), so use sparingly.

**Comment by bartekn** [comment]
So we created `base` and `sdk` packages because we wanted to separate low-level code: `base` (creating operations, transactions etc.) from submitting transactions to _some_ server and querying ledger data: `sdk`. Right now, the most popular server to interact with Stellar is [horizon](https://github.com/stellar/horizon) but we know some developers are working on their implementations.

`TransactionBuilderAccount` interface was created to support other libraries that will appear in the future. So every class that represents account data returned by a _future_ server which implements `TransactionBuilderAccount` can be directly used in `TransactionBuilder` (without having to build `base` object that represents Account).

Does it makes sense or do you still think this interface is a bad idea?

**Comment by myrle-krantz** [comment]
It makes sense under the assumption that you will create a future server.  There are other solutions to that problem if you were to decide to do it that are transparent to the end user (me).  Right now, I suspect you are overdesigning, and that your future problems will probably be entirely different than what you think now.
However I may not have a full view of the requirements you are addressing.

(If you want to know what I mean by "other solutions", I can describe it to you offline sometime. But those would probably fall under the category overdesigning as well.)
